### ISSUE TITLE
chunk gen taking abnormally long

### ISSUE THREAD

**Issue by Ajw2003** [Apothicon02/Biospherical-Expansion#1]
![2023-12-27_23 29 14](https://github.com/Apothicon02/Biospherical-Expansion/assets/79066376/9af9a807-fe85-43e0-b7de-7b3a6b305232)

terrain loading gets stuck like this often, allocated 8gb of ram running only embeddium and modern fix along side which cause no issues with any other world gen mods I've tested thus far.

system is running a 5800x3d, 980 pro ssd, rtx 3080 fe and 32gb of 3200mhz ram, I know minecraft is unoptimized at the best of times, but in comparison to a mod like biomes o plenty, william wythers overhauled overworld, or even other data packs such as tectonic and arboria; world generatation albeit beautiful, feels substantially more slugish.

not sure what the issue is, other than perhaps further optimization needed, however I figured I'd make this post and see if the creator of this beautiful terrain gen had any advice to make it hang on generation of new chunks less

**Comment by Apothicon02** [comment]
Doesn't happen for me with a 12600k + 3080fe, but others have reported the same issue as you. No clue what causes it, as this is effectively just a datapack and only needs to be a mod for the custom blocks and trees.  Only workaround is to pre-generate the world.

**Comment by Apothicon02** [comment]
Solved with new performance preset (the cause is biome-specific terrain)
