### ISSUE TITLE
Single biome worlds generate with vast oceans

### ISSUE THREAD

**Issue by AntonSax** [Apothicon02/Biospherical-Expansion#2]
I created a Single Biome world with the Dark Plains biome. The village I spawned in was in the 'ocean' with the only land the village structure generates. Flying away from it across the ocean I found land and coincidentally this Woodland Mansion.
Note that the world still believes that the oceans are the 'dark plains' biome.

![2024-07-08_11 41 49](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/cc368665-6f19-4db3-acc1-9900367cbfcb)

**Comment by AntonSax** [comment]
I felt this was even easier to see in a Single Biome world using the Windswept Highlands biome.

**Comment by Apothicon02** [comment]
single biome worlds are not supported
