### ISSUE TITLE
Even in a Large Biomes world, biomes can generate only a couple of blocks wide.

### ISSUE THREAD

**Issue by AntonSax** [Apothicon02/Biospherical-Expansion#3]
The best way to understand this is just to see it for yourself in a large biomes world, but I'll try to include pictures of what I am experiencing.

___
A Windswept Highlands biome, which I found by using `/locate biome biox:windswept_highlands`

![2024-07-08_12 02 21](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/36d1b9f9-dd75-43a0-b26b-12e5644b4c47)

___
I think the very small amount of red color makes it clear that the Windswept Highlands biome doesn't extend very far.

![2024-07-08_12 02 26](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/dac61bd8-8404-41d2-9800-76880d086d53)
![2024-07-08_12 02 37](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/0fdc4d57-9a6d-48bd-9910-0fc615c29a10)

___
There are plains next to it, however there is seemingly also a few dirt blocks of Popping Plains that extend between two chunks, but don't even consist of enough blocks to fill a chunk on its own.

![2024-07-08_12 03 11](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/8374cafd-b09b-480f-87f1-ce8b081b7b9b)
![2024-07-08_12 02 46](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/a5e35f08-bf9c-4dae-90e1-9e71b0e73baf)

**Comment by Apothicon02** [comment]
Not fixable.
