### ISSUE TITLE
Fungal Hills will generate trees and huge mushrooms underwater

### ISSUE THREAD

**Issue by AntonSax** [Apothicon02/Biospherical-Expansion#4]
Maybe this isn't a bug and is actually intentional, but I thought I might as well report it anyway.

In oceans of a Single Biome Fungal Hills world, the trees and giant mushrooms will generate on the ocean floor.
Related to #2 and perhaps would be fixed if #2 is fixed.

Biospherical Expansion 1.20.x-2.1.1

![2024-07-08_13 21 55](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/d85b1c6f-5dd2-4075-865d-5c31e5e06166)
![2024-07-08_13 22 10](https://github.com/Apothicon02/Biospherical-Expansion/assets/9059836/cda79a9c-5559-439c-8d6d-9bb7e65b9819)

**Comment by Apothicon02** [comment]
single biome worlds are not supported, but that looks cool anyways
