### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by ALEILGOD** [Apothicon02/Biospherical-Expansion#5]
For mods i have Embeddium, Ecospherical Expansion and Biospherical Expansion. When i try to create a new world the generation is stuck at 0% and completely black. I'm using version 2.1.1 forge 1.20.1 version 47.3.0. I'm on Windows 11 and i have 4gb of ram allocated.
Here is a screenshot
![Screenshot 2024-07-22 105725](https://github.com/user-attachments/assets/561d7420-3a08-4932-a36e-e20a6ccf516b)
and here is the log
https://mclo.gs/pm7cbc1

**Comment by ALEILGOD** [comment]
https://mclo.gs/pm7cbc1

**Comment by Apothicon02** [comment]
Probably just didnt wait long enough, there’s nothing in the log
