### ISSUE TITLE
Weird cubic generation

### ISSUE THREAD

**Issue by jaimarl** [Apothicon02/Biospherical-Expansion#6]
Sometimes generation from smooth becomes cubic. Is it a bug or is it designed that way?
![2024-07-27_18 15 31](https://github.com/user-attachments/assets/0a1f16f0-a4c7-4f1c-a0b7-79abab062352)
![2024-07-27_18 27 55](https://github.com/user-attachments/assets/b59c3083-8203-44e8-916a-1be0f70b7237)
![2024-07-27_18 28 19](https://github.com/user-attachments/assets/84821494-529f-42d3-824b-b363855ac5fb)

**Comment by Apothicon02** [comment]
intentional
